version: "3.8"

services:

  configserver:
    image: sidsol7/bankapp:configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - easybank    
      
  accounts:
    image: sidsol7/bankapp:accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - easybank
    depends_on:    
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071      
      
  loans:
    image: sidsol7/bankapp:loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - easybank
    depends_on:    
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      
  cards:
    image: sidsol7/bankapp:cards
    mem_limit: 700m
    ports:
      - "9070:9070"
    networks:
      - easybank
    depends_on:    
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
  
networks:
  easybank:
